AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Demonstrate a basic trivia skill built with the ASK NodeJS SDK
Resources:
  awsserverlessrepositoryalexaskillskitnodejstrivRFPX0UICJHUA:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: Demonstrate a basic trivia skill built with the ASK NodeJS SDK
      MemorySize: 128
      Timeout: 7
      Role: >-
        arn:aws:iam::186946913131:role/aws-serverless-repository-alexaskillskitnodejstriv-GLUDU4WQHWTC
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
