module.exports = {
  /**
   * When editing your questions pay attention to your punctuation.
   * Make sure you use question marks.
   * Make sure the first answer is the correct one.
   * Set at least ANSWER_COUNT answers, any extras will be shuffled in.
   */
  countries: {
    "A": ["Afghanistan", "\u00c4gypten", "\u00c5landinseln", "Albanien", "Algerien",
      "Amerikanisch-Samoa", "Amerikanische Jungferninseln", "Amerikanische \u00dcberseeinseln",
      "Andorra", "Angola", "Anguilla", "Antarktis", "Antigua und Barbuda", "\u00c4quatorialguinea",
      "Argentinien", "Armenien", "Aruba", "Ascension", "Aserbaidschan", "\u00c4thiopien", "Australien"],
    "B": ["Bahamas", "Bahrain", "Bangladesch", "Barbados", "Belarus", "Belgien", "Belize", "Benin", "Bermuda",
      "Bhutan", "Bolivien", "Bonaire, Sint Eustatius und Saba",
      "Bosnien und Herzegowina", "Botsuana", "Brasilien", "Britische Jungferninseln", "Britisches Territorium im Indischen Ozean",
      "Brunei Darussalam", "Bulgarien", "Burkina Faso", "Burundi"],
    "C": ["Cabo Verde", "Ceuta und Melilla", "Chile", "China", "Cookinseln", "Costa Rica", "C\u00f4te d\u2019Ivoire", "Cura\u00e7ao"],
    "D": ["D\u00e4nemark", "Deutschland", "Diego Garcia", "Dominica", "Dominikanische Republik", "Dschibuti"],
    "E": ["Ecuador", "El Salvador", "Eritrea", "Estland"],
    "F": ["Falklandinseln", "F\u00e4r\u00f6er", "Fidschi", "Finnland", "Frankreich", "Franz\u00f6sisch-Guayana",
      "Franz\u00f6sisch-Polynesien", "Franz\u00f6sische S\u00fcd- und Antarktisgebiete"],
    "G": ["Gabun", "Gambia", "Georgien", "Ghana", "Gibraltar", "Grenada", "Griechenland", "Gr\u00f6nland", "Guadeloupe", "Guam", "Guatemala",
      "Guernsey", "Guinea", "Guinea-Bissau", "Guyana"],
    "H": ["Haiti", "Honduras", "Hongkong"],
    "I": ["Indien", "Indonesien", "Irak", "Iran", "Irland", "Island", "Isle of Man", "Israel", "Italien",],
    "J": ["Jamaika", "Japan", "Jemen", "Jersey", "Jordanien"],
    "K": ["Kaimaninseln", "Kambodscha", "Kamerun", "Kanada", "Kanarische Inseln", "Kasachstan", "Katar", "Kenia", "Kirgisistan",
      "Kiribati", "Kokosinseln", "Kolumbien", "Komoren", "Kongo-Brazzaville", "Kongo-Kinshasa", "Kosovo", "Kroatien", "Kuba", "Kuwait"],
    "L": ["Laos", "Lesotho", "Lettland", "Libanon", "Liberia", "Libyen", "Liechtenstein", "Litauen", "Luxemburg"],
    "M": ["Macau", "Madagaskar", "Malawi", "Malaysia", "Malediven", "Mali", "Malta", "Marokko", "Marshallinseln", "Martinique", "Mauretanien",
      "Mauritius", "Mayotte", "Mazedonien", "Mexiko", "Mikronesien", "Monaco", "Mongolei", "Montenegro", "Montserrat", "Mosambik", "Myanmar"],
    "N": ["Namibia", "Nauru", "Nepal", "Neukaledonien", "Neuseeland", "Nicaragua", "Niederlande", "Niger", "Nigeria", "Niue", "Nordkorea",
      "N\u00f6rdliche Marianen", "Norfolkinsel", "Norwegen"],
    "O": ["Oman", "\u00d6sterreich", "Osttimor"],
    "P": ["Pakistan", "Pal\u00e4stinensische Autonomiegebiete", "Palau", "Panama", "Papua-Neuguinea", "Paraguay", "Peru", "Philippinen",
      "Pitcairninseln", "Polen", "Portugal", "Puerto Rico", "Republik Moldau", "R\u00e9union", "Ruanda", "Rum\u00e4nien", "Russland"],
    "S": ["Salomonen", "Sambia", "Samoa", "San Marino", "S\u00e3o Tom\u00e9 und Pr\u00edncipe", "Saudi-Arabien", "Schweden", "Schweiz", "Senegal",
      "Serbien", "Seychellen", "Sierra Leone", "Simbabwe", "Singapur", "Sint Maarten", "Slowakei", "Slowenien", "Somalia", "Spanien", "Spitzbergen",
      "Sri Lanka", "St. Barth\u00e9lemy", "St. Helena", "St. Kitts und Nevis", "St. Lucia", "St. Martin",
      "St. Pierre und Miquelon", "St. Vincent und die Grenadinen", "S\u00fcdafrika", "Sudan", "S\u00fcdgeorgien und die S\u00fcdlichen Sandwichinseln",
      "S\u00fcdkorea", "S\u00fcdsudan", "Suriname", "Swasiland", "Syrien"],
    "T": ["Tadschikistan", "Taiwan", "Tansania", "Thailand", "Togo", "Tokelau", "Tonga", "Trinidad und Tobago", "Tristan da Cunha", "Tschad",
      "Tschechien", "Tunesien", "T\u00fcrkei", "Turkmenistan", "Turks- und Caicosinseln", "Tuvalu"],
    "U": ["Uganda", "Ukraine", "Ungarn", "Uruguay", "Usbekistan"],
    "V": ["Vanuatu", "Vatikan", "Vatikanstadt", "Venezuela", "Vereinigte Arabische Emirate", "Vereinigte Staaten", "Vereinigtes K\u00f6nigreich", "Vereinte Nationen", "Vietnam"],
    "W": ["Wales", "Wallis und Futuna", "Weihnachtsinsel", "Westsahara"],
    "Z": ["Zentralafrikanische Republik", "Zypern"]
  },
  colors: {
    A:
      ['Aliceblau',
        'Antikwei&szlig;',
        'Aquamarin',
        'Azur',
        'Alte spitze'],
    B:
      ['Blau',
        'Beige',
        'Bisquit',
        'Blau',
        'Blauviolett',
        'Braun',
        'Burlywood',
        'Bla&szlig;grau',
        'Bl&uuml;tenwei&szlig;',
        'Bla&szlig;rose',
        'Bla&szlig; goldrute',
        'Bla&szlig;gr&uuml;n',
        'Bla&szlig;t&uuml;rkis',
        'Bla&szlig;violettrot'],
    C: ['Cyan'],
    D:
      ['Deutsch',
        'Dunkelblau',
        'Dunkelcyan',
        'Dunkel goldrute',
        'Dunkelgrau',
        'Dunkelgr&uuml;n',
        'Dunkelkhaki',
        'Dunkelmagenta',
        'Dunkelolivgr&uuml;n',
        'Dunkelorange',
        'Dunkel orchidee',
        'Dunkelrot',
        'Dunkel lachsrosa',
        'Dunkel seegr&uuml;n',
        'Dunkel schieferblau',
        'Dunkel schiefergrau',
        'Dunkelt&uuml;rkis',
        'Dunkelviolett',
        'Dunkelrosa',
        'Dunkelhimmelblau',
        'Distel'],
    E: ['Elfenbein'],
    F: ['Fuchsie', 'Farbe', 'Fr&uuml;hlingsgr&uuml;n'],
    G:
      ['Grau',
        'Gr&uuml;n',
        'Gelb',
        'Gainsboro',
        'Geisterwei&szlig;',
        'Gold',
        'Goldrute',
        'Grau',
        'Gr&uuml;n',
        'Gr&uuml;ngelb',
        'Grasgr&uuml;n',
        'Gelb',
        'Gelbgr&uuml;n'],
    H:
      ['Honigtau',
        'Hellblau',
        'Hellkorall',
        'Hellcyan',
        'Hellgoldrute',
        'Hellgoldrutengelb',
        'Hellgrau',
        'Hellgr&uuml;n',
        'Hellrosa',
        'Hellmeergr&uuml;n',
        'Hellhimmelblau',
        'Hellschieferblau',
        'Hellschiefergrau',
        'Hellstahlblau',
        'Hellgelb',
        'Himmelblau',
        'Hautfarben'],
    I: ['Indischrot'],
    K:
      ['Kastanienbraun',
        'Krickentengr&uuml;n',
        'Kadettenblau',
        'Korallenrot',
        'Kornblumenblau',
        'Kornseide',
        'Knallrosa',
        'Khaki',
        'K&ouml;nigsblau'],
    L:
      ['Limone',
        'Lila',
        'Lik&ouml;rgr&uuml;n',
        'Lavendel',
        'Lavendelhauch',
        'Limonengr&uuml;n',
        'Leinen',
        'Lila',
        'Lachsrosa'],
    M:
      ['Marine',
        'Mandelwei&szlig;',
        'Magenta',
        'Mittelaquamarinblau',
        'Mittelblau',
        'Mittelorchidee',
        'Mittellila',
        'Mittelseegr&uuml;n',
        'Mittelschieferblau',
        'Mittelfr&uuml;hlingsgr&uuml;n',
        'Mittelt&uuml;rkis',
        'Mittelviolettrot',
        'Mitternachtsblau',
        'Mokassin',
        'Meergr&uuml;n',
        'Muschelwei&szlig;'],
    N: ['Navajo wei&szlig;', 'Navy', 'Navyblau'],
    O: ['Oliv', 'Olivegrau', 'Orange', 'Orangerot', 'Orchidee'],
    P:
      ['Persenningblau',
        'Pfefferminzcreme',
        'Papaya creme',
        'Pfirsich',
        'Peru',
        'Pflaume',
        'Pulverblau'],
    R: ['Rot', 'Rosa', 'Rot', 'Rosigbraun', 'Rauch'],
    S:
      ['Schwarz',
        'Silber',
        'Schwarz',
        'Schokolade',
        'Schamottestein',
        'Sattelbraun',
        'Sandbraun',
        'Sienna',
        'Schieferblau',
        'Schiefergrau',
        'Schneewei&szlig;',
        'Stahlblau'],
    T: ['Tomate', 'T&uuml;rkis'],
    V: ['Violett', 'Violettrot'],
    W: ['Wasser', 'Wei&szlig;', 'Waldgr&uuml;n', 'Weizen', 'Wei&szlig;'],
    Z: ['Zitronenchiffon']
  },
  animals: {
    "A": ["Affe", "Afrikanische eierschlange", "Afrikanischer elefant", "Afrikanischer marabu", "Afrikanischer nimmersatt", "Afrikanischer wildhund", "Afrikanische zwergglanzente", "Aga kröte", "Alaotra halbmaki", "Aldabra riesenschildkröte", "Alet", "Alpaka", "Amazonas delphin", "Amazonasente", "Ameisenbär", "Amurtiger", "Anemonenfisch", "Antilope", "Antilope", "Arabische oryx", "Ararauna", "Arktischer wolf", "Asiatischer elefant", "Asiatischer löwe", "Asiatischer zwergotter", "Assapan", "Atlantischer ammenhai", "Ausgestorbene tiere", "Australischer lungenfisch", "Azurkopftangare", "Afrikanischer elefant", "Asiatischer elefant", "Aga kröte", "Asiatischer zwergotter", "Asiatischer löwe", "Afrikanischer marabu", "Afrikanischer nimmersatt", "Aldabra riesenschildkröte", "Afrikanische eierschlange", "Alle arten", "Afrikanischer wildhund", "Affenpinscher", "Afghanischer windhund", "Agassin", "Airedale terrier", "Akita", "Aksaray malaklısı", "Alano español", "Alaskan malamute", "Alaskan husky", "Alaunt", "Alpenländische dachsbracke", "Altdänischer vorstehhund", "Altdeutsche hütehunde", "Altdeutscher schäferhund", "American akita", "American blue gascon hound", "American bulldog", "American eskimo dog", "American foxhound", "American hairless terrier", "American leopard hound", "American pit bull terrier", "American staffordshire terrier", "American staghound", "American toy terrier", "American water spaniel", "Amerikanischer cocker spaniel", "Anglo-français de petite vénerie", "Appenzeller sennenhund", "Ariégeois", "Armant", "Australian cattle dog", "Australian cattle dog", "Australian kelpie", "Australian shepherd", "Australian silky terrier", "Australian stumpy tail cattle dog", "Australian terrier", "Azawakh", "Ardennen-treibhund", "Anatolischer hirtenhund", "American foxhound", "Altdänischer vorstehhund", "Anatolischer hirtenhund", "Anatolischer hirtenhund", "Australian kelpie", "American leopard hound", "Aksaray malaklısı", "Affenpinscher", "Australian silky terrier", "American cocker spaniel", "American water spaniel", "American eskimo dog", "Azawakh", "Aksaray malaklısı", "Afghanischer windhund", "Azawakh", "Australian kelpie", "Abessinier", "American bobtail shorthair", "American curl shorthair", "American shorthair", "American wirehair", "Anatoli", "Arabische mau", "Asian", "Australian mist", "American bobtail longhair", "American curl longhair", "Angorakatze"],
    "B": ["Bahamaente", "Baikalente", "Balistar", "Banteng", "Bär", "Brillenbär", "Bär", "Bärenstümmelaffe", "Bartaffe", "Bartgeier", "Bartkauz", "Bartschi anolis", "Baumpieper", "Beilbauchfisch", "Bengalracke", "Bengaltiger", "Bennett känguruh", "Bernierente", "Beutelfrosch", "Bindenwaran", "Bison", "Blauer malawi buntbarsch", "Blauer pfau", "Blauer pfeilgiftfrosch", "Blauflügel prachtlibelle", "Blaukopf erdracke", "Blauzungenskink", "Blessbock", "Bongo", "Bonobo", "Borneo orang utan", "Brandgans", "Brasilianischer riesenotter", "Brasilianische zwergralle", "Braunkehlpfäffchen", "Braunkopfschaf", "Braunrückentamarin", "Brautente", "Brazza meerkatze", "Breitmaulnashorn", "Brillenbär", "Brillenpinguin", "Bucharahirsch", "Burma leierhirsch", "Bürstenkänguruh", "Beutelfrosch", "Blauer pfeilgiftfrosch", "Bengaltiger", "Breitmaulnashorn", "Borneo orang utan", "Bambusbär", "Berger blanc suisse", "Bakarwal", "Balkanbracke", "Bandog", "Barbet", "Basenji", "Basset artésien normand", "Blauer basset der gascogne", "Basset d’artois", "Basset fauve de bretagne", "Basset hound", "Bullenbeißer", "Bayerischer gebirgsschweißhund", "Beagle", "Beagle-harrier", "Bearded collie", "Beauceron", "Bedlington terrier", "Belgischer schäferhund", "Bergamasker hirtenhund", "Berger blanc suisse", "Beauceron", "Berger du languedoc", "Berger de picardie", "Berger de savoie", "Berner sennenhund", "Bernhardiner", "Bichon frisé", "Biewer terrier", "Billy", "Bisben", "Black and tan coonhound", "Black mouth cur", "Blue lacy", "Bluetick coonhound", "Bobtail", "Boerboel", "Bologneser", "Bolonka franzuska", "Bolonka zwetna", "Bordeauxdogge", "Border collie", "Border terrier", "Boston terrier", "Bouvier des flandres", "Boykin spaniel", "Bracco italiano", "Brandlbracke", "Braque belge", "Braque d’auvergne", "Braque de l’ariège", "Braque du bourbonnais", "Braque dupuy", "Braque français", "Braque dupuy", "Braque saint-germain", "Briard", "Briquet de provence", "Briquet griffon vendéen", "Broholmer", "Bullenbeißer", "Bullmastiff", "Bull terrier", "Black and tan coonhound", "Bluetick coonhound", "Bull terrier", "Billy", "Belgischer schäferhund", "Bloodhound", "Bracco italiano", "Berger blanc suisse", "Blue lacy", "Belgischer schäferhund", "Belgischer schäferhund", "Berger de picardie", "Barsoi", "Berner laufhund", "Black mouth cur", "Boykin spaniel", "Bernhardiner", "Bichon frisé", "Blue lacy", "Berger blanc suisse", "Barsoi", "Black mouth cur", "Bull terrier", "Bengal", "Bombay", "Brasilianisch kurzhaar", "Britisch kurzhaar", "Burma", "Burmilla", "Balinese", "Britisch langhaar (highlander)", "Birma", "Bohemian rex", "Bezeichnung"],
    "C": ["Capybara", "Chihuahua", "Ceylon hutaffe", "Chapman steppenzebra", "Chileflamingo", "Chinchilla", "Chinesischer muntjak", "Chinesische zwergwachtel", "Coburger fuchsschaf", "Chinesischer muntjak", "Chapman steppenzebra", "Chien de saint-hubert", "Ca de bestiar", "Ca de bou", "Ca rater mallorquí", "Cairn terrier", "Cane corso italiano", "Cane pastore di oropa", "Cane da pastore bergamasco", "Caravan hound", "Carolina dog", "Catahoula bulldog", "Cavalier king charles spaniel", "Chambray", "Chart polski", "Chesapeake bay retriever", "Chien d’artois", "Chien de montagne des pyrénées", "Chien de trait belge", "Chihuahua", "Chinese chongqing dog", "Chinesischer schopfhund", "Chinook", "Chippiparai", "Chodský pes", "Chinese chongqing dog", "Chow-chow", "Cirneco dell’etna", "Clumber spaniel", "Collie", "Combai", "Continental bulldog", "Coonhound", "Coton de tuléar", "Curly coated retriever", "Cursinu", "Chortaj", "Ciobănesc românesc mioritic", "Ca de bestiar", "Ca de bou", "Chart polski", "Cão da serra de aires", "Cão de água português", "Chesapeake bay retriever", "Curly coated retriever", "Collie", "Cavalier king charles spaniel", "Clumber spaniel", "Chart polski", "California spangled", "Ceylon-katze", "Chartreux", "Chausie", "Cornish rex", "Chantilly", "Cymric", "Colourpoint"],
    "D": ["Döbel", "Dachs", "Damara steppenzebra", "Davidshirsch", "Delphin", "Diana meerkatze", "Doppelhornvogel", "Dschelada", "Delphin", "Dunkle pelomedusen sumpfschildkröte", "Der weiße hai", "Dogo argentino", "Deutscher boxer", "Dackel", "Dalmatiner", "Dandie dinmont terrier", "Deutsche dogge", "Dansk-svensk gårdshund", "Deerhound", "Deutsch drahthaar", "Deutsch kurzhaar", "Deutsch langhaar", "Deutsch stichelhaar", "Deutsche bracke", "Deutsche dogge", "Deutscher boxer", "Deutscher jagdterrier", "Deutscher pinscher", "Deutscher schäferhund", "Deutscher wachtelhund", "Dingo", "Do khyi", "Dobermann", "Dogo argentino", "Dogo canario", "Dreifarbiger serbischer laufhund", "Drentse patrijshond", "Drever", "Deutscher schäferhund", "Dunker", "Deutscher spitz", "Dogo canario", "Dogo canario", "Deutscher pinscher", "Dobermann", "Dackel", "Drahthaariger ungarischer vorstehhund", "Deutscher wachtelhund", "Deerhound", "Dackel", "Dackel", "Devon rex", "Don sphynx", "Deutsch langhaar"],
    "E": ["Eichhörnchen", "Eiderente", "Eisbär", "Eisfuchs", "Elefant", "Elefant", "Emu", "Engel fiederbartwels", "Englisches vollblut", "Erckelfrankolin", "Erdmännchen", "Eulenkopfmeerkatze", "Eurasischer luchs", "Eurasische zwergmaus", "Europäischer fischotter", "Europäischer uhu", "Europäische sumpfschildkröte", "Europäische wildkatze", "Eurasische zwergmaus", "Europäische sumpfschildkröte", "Europäischer uhu", "English coonhound", "Englische bulldogge", "English cocker spaniel", "English coonhound", "Estnischer laufhund", "Elo", "Englische bulldogge", "English cocker spaniel", "English coonhound", "English foxhound", "English pointer", "English setter", "English shepherd", "English springer spaniel", "English toy terrier", "Estnischer laufhund", "Entlebucher sennenhund", "Epagneul breton", "Epagneul bleu de picardie", "Epagneul de pont-audemer", "Epagneul de saint-usuge", "Epagneul français", "Epagneul picard", "Erdélyi kopó", "Eskimohund", "Eurasier", "Europäischer schlittenhund", "Epagneul français", "English setter", "English springer spaniel", "English pointer", "English coonhound", "Europäischer schlittenhund", "Epagneul breton", "English cocker spaniel", "English springer spaniel", "Epagneul français", "Erdélyi kopó", "Europäisch kurzhaar", "Exotic shorthair", "Exotic longhair"],
    "F": ["Falkland dampfschiffente", "Färberfrosch", "Felsenleguan", "Felsensittich", "Felsentaube", "Fischertukan", "Fischerturako", "Fisch", "Fischotter", "Flachlandgorilla", "Flachlandtapir", "Flachland viscacha", "Flammenkopf bartvogel", "Fledermaus", "Fledermausfisch", "Flösselhecht", "Flusspferd", "Fluss seeschwalbe", "Fossa", "Fratzenkuckuck", "Frettchen", "Frösche", "Frosch", "Frosch", "Frosch", "Frosch", "Frosch", "Frosch", "Frosch", "Frosch", "Fuchs", "Flachlandgorilla", "Fila brasileiro", "Field spaniel", "Fila brasileiro", "Finnenbracke", "Finnischer lapphund", "Finnischer spitz", "Flat coated retriever", "Foxterrier", "Foxterrier", "Foxterrier", "Französische bulldogge", "Französische laufhunde", "Französischer laufhund", "Französischer laufhund", "Französischer laufhund", "Französischer vorstehhund", "Finnischer spitz", "Foxterrier", "Flat-coated retriever", "Field spaniel", "Finnischer lapphund", "Foldex", "Foreign white"],
    "G": ["Goldener pfeilgiftfrosch", "Gabelbart", "Gabelracke", "Galapagos riesenschildkröte", "Gänsegeier", "Gaur", "Gebänderter fidschi leguan", "Gefleckter knochenhecht", "Gelbbrustkapuziner", "Gelbbürzelkassike", "Gelber segeldoktorfisch", "Gelbschnabelente", "Geoffroy klammeraffe", "Gepard", "Gespenstschrecken", "Gestreifter zwergkaiserfisch", "Gewöhnlicher kormoran", "Gewöhnlicher rotfeuerfisch", "Gewöhnliches stachelschwein", "Giraffe", "Glattrand gelenkschildkröte", "Goldaguti", "Gold baumsteiger", "Goldener pfeilgiftfrosch", "Goldgelbes löwenäffchen", "Goldkopflöwenäffchen", "Goodman mausmaki", "Gorilla", "Gorilla", "Granit zaunleguan", "Grauflügel trompetervogel", "Graugans", "Grauköpfchen", "Grau marmorierter buntbarsch", "Graupapagei", "Grevy zebra", "Griechische landschildkröte", "Grizzly bär", "Großer ameisenbär", "Großer bambuslemur", "Großer doktorfisch", "Großer igeltanrek", "Großer kodu", "Großer madagaskar taggecko", "Großer mara", "Großer tümmler", "Große weißnasenmeerkatze", "Grüne demoiselle", "Grünflügelara", "Grünhelmturako", "Grüner leguan", "Guanako", "Guereza", "Gürtelvari", "Galapagos riesenschildkröte", "Glattrand gelenkschildkröte", "Gelbbacke", "Griffon belge", "Groenendael", "Griffon à poil laineux", "Griffon bruxellois", "Griechischer schäferhund", "Grand anglo-français", "Grand anglo-français", "Grand anglo-français", "Grand bleu de gascogne", "Grand gascon saintongeois", "Grand griffon vendéen", "Griffon fauve de bretagne", "Griffon nivernais", "Galgo español", "Gelbbacke", "Glen of imaal terrier", "Goldendoodle", "Golden retriever", "Gończy polski", "Gordon setter", "Gos d’atura català", "Gråhund", "Grand anglo-français", "Grand anglo-français", "Grand anglo-français", "Grand basset griffon vendéen", "Grand bleu de gascogne", "Grand gascon saintongeois", "Grand griffon vendéen", "Great japanese dog", "Greyhound", "Griechischer schäferhund", "Griffon à poil dur", "Griffon à poil laineux", "Griffon belge", "Griffon bleu de gascogne", "Griffon à poil laineux", "Griffon bruxellois", "Griffon fauve de bretagne", "Griffon à poil dur", "Griffon nivernais", "Grönlandhund", "Großer münsterländer", "Grosser schweizer sennenhund", "Glatthaar-foxterrier", "Großer münsterländer", "Golden retriever", "Galgo español", "Galgo español", "Greyhound", "German rex"],
    "H": ["Hunde", "Hagedasch", "Haie", "Haiwels", "Halsbandkotinga", "Halsbandliest", "Halsband tschaja", "Halsband wehrvogel", "Hammerkopf", "Hartlaubsturako", "Hausesel", "Hauskamel", "Hawaiigans", "Helmkasuar", "Himalaya glanzfasan", "Hirschziegenantilope", "Hispaniola anolis", "Hopftaube", "Hornrabe", "Hottentottenente", "Hühnergans", "Humboldtpinguin", "Hund", "Hyäne", "Humboldt pinguin", "Harzer fuchs", "Hortaya borzaya", "Hybridhund", "Hellinikos ichnilatis", "Haldenstøver", "Hallstrom-hund", "Hamiltonstövare", "Hannoverscher schweißhund", "Harlekinpinscher", "Harrier", "Harzer fuchs", "Havaneser", "Hawaiian poi dog", "Hellinikos ichnilatis", "Hertha pointer", "Hirtenhund der abruzzen", "Hokkaido-hund", "Holländischer schäferhund", "Hollandse smoushond", "Hovawart", "Hrvatski ovčar", "Hybridhund", "Hygenhund", "Hollandse herdershond", "Havana"],
    "I": ["Igel", "Impala", "Indischer glaswels", "Indischer löwe", "Insekten", "Irischer wolfshund", "Irish red and white setter", "Irish red setter", "Irish soft coated wheaten terrier", "Irish terrier", "Irish water spaniel", "Isländischer schäferhund", "Italienisches windspiel", "Irish soft coated wheaten terrier", "Irish water spaniel", "Italienischer kleinspitz", "Irischer wolfshund", "Italienisches windspiel", "Italienisches windspiel", "Irish wolfhound"],
    "J": ["Jaguar", "Jemenchamäleon", "Jungfernkranich", "Japan chin", "Jack russell terrier", "Jakutischer laika", "Jämthund", "Japan chin", "Japanischer terrier", "Japan-spitz", "Jonangi", "Jugoslawischer dreifarbiger laufhund", "Jugoslawischer gebirgslaufhund", "Jakutischer laika", "Jura laufhund", "Japanese bobtail shorthair", "Javanese", "Japanese bobtail longhair"],
    "K": ["Kurzkrallenotter", "Königstiger", "Kaffernhornrabe", "Kaisergans", "Kaiserschnurrbart tamarin", "Kalifornischer seelöwe", "Kampfläufer", "Kanadagans", "Känguruh", "Kanincheneule", "Kapente", "Kappenblaurabe", "Kappengibbon", "Kaptriel", "Katta", "Katze", "Kegelrobbe", "Kennyi mbuna", "Kiemenschlitzaal", "Kinnfleck schmuckschildkröte", "Kirkdikdik", "Kleideraffe", "Kleiner panda", "Kleiner paradiesvogel", "Kleiner vasapapagei", "Klippspringer", "Knochenhecht", "Koala", "Kodiakbär", "Köhlerschildkröte", "Kolbenente", "Kongopapagei", "Kongopfau", "Kongosalmler", "Königsglanzfasan", "Königspinguin", "Königspython", "Königstiger", "Korallenfingerfrosch", "Kornnatter", "Kragenbär", "Kragenechse", "Krickente", "Krokodil", "Krokodil", "Kronenkranich", "Kronenmaki", "Kröte", "Kuhreiher", "Kupferspiegelente", "Kurzkrallenotter ", "Kinnfleck schmuckschildkröte", "Königspython", "Kornnatter", "Kleiner vasapapagei", "Kuhhund", "Kangal-hirtenhund", "King-charles-spaniel", "Kurzhaarcollie", "Kleinspitz", "Keeshond", "King charles spaniel", "Karst-schäferhund", "Kurzhaarige istrianer bracke", "Kai", "Kaikadi", "Kanaanhund", "Karakatschan", "Karelischer bärenhund", "Karst-schäferhund", "Katalanischer schäferhund", "Kaukasischer owtscharka", "Keltenbracke", "Kerry beagle", "Kerry blue terrier", "King charles spaniel", "Kintamani", "Kishu", "Kleiner münsterländer", "Kleinspitz", "Komondor", "Kontinentaler zwergspaniel", "Kooikerhondje", "Kopov", "Korea jindo dog", "Kraški ovčar", "Kritikos lagonikos", "Kroatischer schäferhund", "Kromfohrländer", "Kurzhaarcollie", "Kurzhaarige istrische bracke", "Kuvasz", "Kyi leo", "Kaukasischer owtcharka", "Kontinentaler zwergspaniel", "Kelb tal-fenek", "Kerry beagle", "King-charles-spaniel", "King-charles-spaniel", "Kuhhund", "Kurzhaarcollie", "King charles spaniel", "Kontinentaler zwergspaniel", "Kurzhaariger ungarischer vorstehhund", "Kuhhund", "Keeshond", "Kanaani", "Khao manee", "Korat", "Kurilen bobtail", "Karelian bobtail longhair", "Kurilen bobtail", "Kartäuser-katze"],
    "L": ["Lippenbär", "Lachender hans", "Lachsroter regenbogenfisch", "Lama", "Leopard", "Leopard", "Leopard", "Leopardfrosch", "Lilfordkranich", "Lippenbär", "Lisztaffe", "Lisztäffchen", "Löffelente", "Löwe", "Löwe", "Langhaarcollie", "Laekenois", "Laekenois", "Louisiana catahoula leopard dog", "Langhaarcollie", "Lappländischer rentierhund", "Labradoodle", "Labrador retriever", "Lagotto romagnolo", "Laika", "Laika", "Laika", "Laika", "Lakeland terrier", "Lancashire heeler", "Landseer", "Langhaarcollie", "Longhaired whippet", "Lapphund", "Lappländischer rentierhund", "Leonberger", "Lettische bracke", "Levesque", "Lhasa apso", "Longdog", "Longhaired whippet", "Louisiana catahoula leopard dog", "Löwchen", "Lupo italiano", "Lurcher", "Luzerner laufhund", "Labrador retriever", "Langhaarcollie", "Luzerner laufhund", "Longhaired whippet", "Laika", "La perm shorthair", "La perm longhair", "Langhaarkatzen"],
    "M": ["Madagaskar barsch", "Madagaskar brillenvogel", "Madagaskar dajal", "Madagaskar drongo", "Madagaskar ente", "Madagaskar hundskopfboa", "Madagaskar perlwachtel", "Madagaskar ratte", "Madagaskar schildechse", "Madagaskarweber", "Madagaskar barsch", "Mähnenspringer", "Mähnenwolf", "Malaienbär", "Malaien hornvogel", "Mandarinente", "Mandarinfisch", "Mandrill", "Mandschurenkranich", "Mantelpavian", "Manul", "Marabu", "Marakeli buntbarsch", "Maskenkiebitz", "Masken schmetterlingsfisch", "Massai strauß", "Matschie baumkänguruh", "Maus", "Meerschweinchen", "Mellers riesenchamäleon", "Mellers riesenchamäleon", "Mittelamerikanischer tapir", "Moorente", "Moschusochse", "Moskitofisch", "Motmot", "Muntjak", "Mustang", "Moschusochse", "Madagaskar hundskopfboa", "Mongolischer wolf", "Miniature american shepherd", "Majorero canario", "Malinois", "Maremmaner hirtenhund", "Mastino napoletano", "Malamut", "Malteser", "Manchester terrier", "Maremmaner hirtenhund", "Markiesje", "Mastiff", "Mastín del pirineo", "Mastín español", "Mastino napoletano", "Mâtin", "Mcnab", "Miniature american shepherd", "Miniature bull terrier", "Mittelasiatischer schäferhund", "Molosser", "Montenegrinischer gebirgslaufhund", "Mops", "Moskauer wachhund", "Mucuchies", "Mudhol hound", "Mudi", "Majorero canario", "Majorero canario", "Mops", "Mastín del pirineo", "Mastín español", "Mittelasiatischer tazi", "Mudi", "Magyar agár", "Magyar agár", "Mittelasiatischer schäferhund", "Manx", "Mekong bobtail", "Minskin", "Munchkin shorthair", "Maine coon", "Mandarin", "Munchkin longhair", "Malteserkatze"],
    "N": ["Nilkrokodil", "Nacktnasenwombat", "Nandu", "Nasenbär", "Nashorn", "Nashorn", "Nashorn", "Nashorn", "Natters sägesalmler", "Nebelparder", "Netzgiraffe", "Netzpython", "Neukaledonischer riesengecko", "Nilgans", "Nilkrokodil", "Nimmersatt", "Nordamerikanischer waschbär", "Netzpython", "Nordamerikanischer waschbär", "Norwegischer buhund", "Neuguinea-dingo", "Neuseeländischer huntaway", "Norwegischer lundehund", "Neufundländer", "Neuseeländischer huntaway", "Norfolk terrier", "Normand-poitevin", "Norrbottenspitz", "Norwegischer buhund", "Norwegischer elchhund grau", "Norwegischer elchhund schwarz", "Norwegischer lundehund", "Norwich terrier", "Nova scotia duck tolling retriever", "Nova scotia duck tolling retriever", "Nebelung", "Neva masquarade", "Norwegische waldkatze", "Non pointed himalayan"],
    "O": ["Oryx antilope", "Ostafrikanisches spitzmaulnashorn", "Ochse", "Okapi", "Onager", "Orang utan", "Orang utan", "Orang utan", "Oryx antilope", "Ostafrikanisches spitzmaulnashorn", "Old english black and tan terrier", "Old white english terrier", "Olde english bulldogge", "Osteuropäischer schäferhund", "Otterhund", "Owtscharka", "Ogar polski", "Ocicat", "Ojos azules", "Oregon rex", "Orientalisch kurzhaar", "Ojos azules langhaar", "Orientalisch langhaar"],
    "P": ["Pfeilgift frösche", "Persischer leopard", "Panzernashorn", "Pacu", "Paletten doktorfisch", "Palmkakadu", "Panda", "Pantherchamäleon", "Panzernashorn", "Papagei", "Papstfink", "Paradieskranich", "Paraguay anakonda", "Peposakaente", "Pfeilgiftfrösche", "Persische kropfgazelle", "Persischer leopard", "Pferd", "Pinguin", "Pinguin", "Pinselohrschwein", "Pinzetten doktorfisch", "Pitpit", "Plattschwanzgecko", "Prachtglanzstar", "Prachtschmerle", "Präriebison", "Präriehund", "Prévost schönhörnchen", "Pudu", "Purpurglanzstar", "Purpurtangarer", "Putzerfisch", "Paraguay anakonda", "Podenco ibicenco", "Pyrenäenschäferhund", "Petit brabançon", "Portugiesischer wasserhund", "Plott hound", "Poitevin", "Pudel", "Peruanischer nackthund", "Pharaoh hound", "Pudel", "Pudel", "Podenco andaluz maneto", "Pachon navarro", "Paleiyakaran", "Pariahund", "Parson russell terrier", "Pastor garafiano", "Pastor vasco", "Patterdale terrier", "Pekingese", "Perdigueiro português", "Perdiguero de burgos", "Perro de agua español", "Peruanischer nackthund", "Petit basset griffon vendéen", "Petit bleu de gascogne", "Petit brabançon", "Petit gascon saintongeois", "Phu quoc ridgeback", "Pinscher", "Plott hound", "Podenco", "Podenco andaluz", "Podenco andaluz maneto", "Podenco canario", "Podenco ibicenco", "Podengo português", "Poitevin", "Polnische bracke", "Polski owczarek nizinny", "Polski owczarek podhalanski", "Pommersche hütehunde", "Polnischer niederungshütehund", "Porcelaine", "Prager rattler", "Prager rattler", "Pudel", "Pudelpointer", "Puli", "Pumi", "Puwo", "Pyrenäen-berghund", "Pyrenäenschäferhund", "Pyrenäenschäferhund", "Perro de agua español", "Perro de ganado majorero", "Peterbald", "Pixiebob shorthair", "Pixiebob longhair", "Perser"],
    "Q": ["Qualle", "Quastenflosser"],
    "R": ["Roter pfeiffrosch", "Rot fuchs", "Rauhfusskauz", "Reichenow weber", "Reiherente", "Rentier", "Riesentrappe", "Riesenzackenbarsch", "Ritteranolis", "Rodriguez flughund", "Rosaflamingo", "Rosapelikan", "Rostgans", "Rotbauchmaki", "Rotbauchtamarin", "Rötelpelikan", "Roter brüllaffe", "Roter dreibinden anemonenfisch", "Roter flamingo", "Roter neon", "Roter pfeiffrosch", "Roter piranha", "Roter sichler", "Roter vari", "Rotes riesenkänguruh", "Rotfuchs", "Rothalsgans", "Rotkopfstärling", "Rotschenkel", "Rotschnabelente", "Rotschnabel madenhacker", "Rotschulterente", "Rotschwanz ährenfisch", "Rotstirnmaki", "Rotwangen schmuckschildkröte", "Rubintyrann", "Rückenschwimmender kongowels", "Russischer windhund", "Redbone coonhound", "Rauhhaarige istrianer bracke", "Rafeiro do alentejo", "Rajapalayam", "Rampur hound", "Rastreador brasileiro", "Rat terrier", "Ratonero bodeguero andaluz", "Ratonero mallorquín", "Ratonero valenciano", "Rauhhaarige istrische bracke", "Redbone coonhound", "Retriever", "Rhodesian ridgeback", "Riesenschnauzer", "Rottweiler", "Russischer schwarzer terrier", "Russkiy toy", "Russischer schwarzer terrier", "Rastreador brasileiro", "Russisch blau", "Ragamuffin", "Ragdoll"],
    "S": ["Saiga antilope", "Schmuckhornfrosch", "Seefrosch", "Sumpfwallaby", "Siam krokodil", "Schneeleopard", "Spitzmaulnashorn", "Sumatranischer orang utan", "Süd pudu", "Säbelschnäbler", "Safranfink", "Saiga antilope", "Saruskranich", "Sattelstorch", "Satyr tragopan", "Schabemaulbuntbarsch", "Schabrackentapir", "Schellente", "Schildkröte", "Schildkröte", "Schildkröte", "Schildkröte", "Schildkröte", "Schildkröte", "Schildkröten", "Schildturako", "Schlange", "Seitenwinder klapperschlange", "Sinaloe königsnatter", "Spitzkopfnatter", "Schmetterlinge", "Schmuckhornfrosch", "Schmutzgeier", "Schnecken", "Schneckenbuntbarsch", "Schnee eule", "Schneeleopard", "Schnurrbart tamarin", "Schopfgibbon", "Schopftinamu", "Schrägschwimmer", "Schützenfisch", "Schwanenfelds barbe", "Schwarzer dreibinden anemonenfisch", "Schwarzstorch", "Schwarz weißer vari", "Seefrosch", "Seehund", "Seepferdchen", "Segelechse", "Seitenwinder klapperschlange", "Seychellen riesenschildkröte", "Siamang", "Siam krokodil", "Sibirischer tiger", "Sibirisches feuerwiesel", "Sichelente", "Siedleragame", "Sinaloe königsnatter", "Sitatunga", "Skorpions krustenechse", "Skudde", "Smaragdeidechse", "Smaragdente", "Sonnenbarsch", "Sonnenralle", "Sonnensittich", "Sperbereule", "Sperlingskauz", "Spinnen", "Spitzhörnchen", "Spitzkopfnatter", "Spitzmaulnashorn", "Spix guan", "Springtamarin", "Starweber", "Steinhuhn", "Störwels", "Strausswachtel", "Streifengans", "Streifen plattschwanzgecko", "Streifenskunk", "Stumpfkrokodil", "St.vincent anolis", "Südamerikanischer nasenbär", "Südamerikanischer seebär", "Sundra pfeifdrossel", "Süd pudu", "Sumatranischer orang utan", "Sumpfwallaby", "Süßwasser rochen", "Schafpudel", "Schwarzer", "Strobel", "Sloughi", "Stichelhaariger bosnischer laufhund", "Schweizer laufhund", "Stichelhaariger bosnischer laufhund – barak", "Spitz", "Spitz", "Spitz", "Spitz", "Siberian husky", "Segugio italiano", "Schweizer laufhund", "Shikoku", "Schnauzer", "Spitz", "Südrussischer owtscharka", "Shar-pei", "Saarlooswolfhund", "Sabueso español", "Saluki", "Samojede", "Sanshu", "Sabsal gae", "Steinbracke", "Save bracke", "Schäferhund", "Schafpudel", "Schapendoes", "Schensihund", "Schillerstövare", "Schipperke", "Schnauzer", "Slovenský kopov", "Schwedischer lapphund", "Schweißhund", "Schweizer laufhund", "Schwyzer laufhund", "Schweizerischer niederlaufhund", "Scottish terrier", "Sealyham terrier", "Segugio italiano", "Segugio italiano", "Segusier", "Serbischer laufhund", "Shar-pei", "Shetland sheepdog", "Shiba-inu", "Shih-tzu", "Shikoku", "Siberian husky", "Silken windhound", "Skye terrier", "Sloughi", "Spaniel", "Sussex spaniel", "Spinone italiano", "Spitz", "Stabyhoun", "Staffordshire bull terrier", "Steinbracke", "Steirische rauhhaarbracke", "Stichelhaariger bosnischer laufhund – barak", "Südrussischer schäferhund", "Sussex spaniel", "Schwarzer terrier", "Saluki", "Sloughi", "Safari", "Savannah", "Scottish fold shorthair", "Selkirk rex shorthair", "Serengeti", "Seychellois shorthair", "Siam", "Singapura", "Snowshoe", "Sokoke", "Sphynx", "Scottish fold longhair", "Selkirk rex longhair", "Seychellois longhair", "Sibirische katze", "Somali", "Snowshoe longhair"],
    "T": ["Tomatenfrosch", "Tüpfelhyäne", "Tannzapfenechse", "Tieflandnyala", "Tomatenfrosch", "Trampeltier", "Trauerpfäffchen", "Trompeterhornvogel", "Tuberkelhokko", "Tundrawolf", "Tüpfelhyäne", "Türkisvogel", "Tiger", "Tuareg-windhund", "Thai bangkaew dog", "Tervueren", "Terrier brasileiro", "Tschechischer berghund", "Tschechischer terrier", "Treeing walker coonhound", "Tschukotskaja jesdowaja", "Tazy", "Tibet spaniel", "Taigan", "Taiwanhund", "Tamaskan", "Tatrahund", "Telomian", "Terrier", "Terrier brasileiro", "Tesem", "Thai bangkaew dog", "Thai ridgeback", "Tibet-spaniel", "Tibet-terrier", "Tibetdogge", "Tiroler bracke", "Torfhund", "Tornjak", "Tosa", "Treeing tennessee brindle", "Treeing walker coonhound", "Tschechischer berghund", "Tschechischer terrier", "Tschechoslowakischer wolfhund", "Tschukotskaja jesdowaja", "Turnspit dog", "Tschechoslowakischer wolfhund", "Thai", "Tonkanese", "Toyger", "Tibeter", "Tiffanie", "Türkisch angora", "Türkisch van", "Türkisch vankedisi"],
    "U": ["Uhu", "Ultramarin bischof", "Ungarischer hirtenhund", "Urhund", "Ural rex", "Ural rex langhaar"],
    "V": ["Vasapapagei", "Vasapapagei", "Vasapapagei", "Vielfrass", "Vikunja", "Vögel", "Volpino italiano", "Vizsla", "Vizsla", "Vizsla", "Västgötaspets", "Villano de las encartaciones", "Villanuco de las encartaciones"],
    "W": ["Westliche sitatunga", "Waldrapp", "Waldschildkröte", "Waschbär", "Waschbär", "Wasseragame", "Wasserschwein", "Westliche sitatunga", "Watussi rind", "Weißbinden anemonenfisch", "Weißbüschelaffe", "Weißflügelente", "Weißgesicht seidenäffchen", "Weißnackenkranich", "Weißkopfmaki", "Weißkopfsaki", "Weißohrenturako", "Weißrücken flötenvogel", "Weißstirnspint", "Weißstorch", "Weißwangengans", "Wespen", "Westafrikanische zwergziege", "Westlicher flachlandgorilla", "Wildhund", "Wildmeerschweinchen", "Wildtruthuhn", "Wimpelfisch", "Wisent", "Witwenente", "Witwenpfeifgans", "Wolf", "Westafrikanische zwergziege", "Welsh corgi pembroke", "Wetterhoun", "Wolfsspitz", "Wolfsspitz", "Welsh springer spaniel", "Wäller", "Weimaraner", "Welsh corgi cardigan", "Welsh corgi pembroke", "Welsh sheepdog", "Welsh springer spaniel", "Welsh terrier", "West highland white terrier", "Westfälische dachsbracke", "Wetterhoun", "Whippet", "Windhund", "Whippet"],
    "X": ["Xoloitzcuintli", "Xoloitzcuintli", "Xoloitzcuintle"],
    "Y": ["Yak", "Yorkshire terrier"],
    "Z": ["Zwergleithörnchen", "Zwerg pinguin", "Zebra", "Zebramanguste", "Zierschildkröte", "Zitronenbuntbarsch", "Zitronenjunker", "Zitteraal", "Zweifarbenjunker", "Zweifingerfaultier", "Zweizehen faultier", "Zwergblessgans", "Zwergesel", "Zwergflusspferd", "Zwergotter", "Zwergpinguin", "Zwergplumplori", "Zwergsäger", "Zwergschwan", "Zwergschwein", "Zwergseidenaffe", "Zwergwabenkröte", "Zwergziege", "Zentralasiatischer owtscharka", "Zwergpinscher", "Zwergpinscher", "Zwergpinscher", "Zwergpudel", "Zwergschnauzer", "Zwergspitz"]
  },
  cars: {
    "A": ["Abarth", "Ac", "Acura", "Ail", "Aixam", "Alfa romeo", "Almac", "Alpha sports", "Alpina", "Alpine", "Alvis", "Amazon", "Americar", "Amuza", "Anchi", "Ariel", "Aro", "As", "Ascari", "Ashok leyland", "Asia rocsta", "Asl", "Aston martin", "Audi", "Autosan", "Avanti", "Abadal", "Adams-farwell", "Adams hewitt", "Adler", "Aero", "Alba", "Alfa", "Allard", "Alta", "Ambassador", "Amber", "American motors", "Amilcar", "Ariès", "Armstrong-siddeley", "Ashley", "Apollo", "Auburn", "Austin", "Austin healey", "Austro daimler", "Autobianchi", "Auto union"],
    "B": ["Baur", "Beijing", "Bellier", "B.engineering", "Bentley", "Birkin", "Bitter", "Bizzarini", "Bmw", "Bristol", "Brocklands", "Brm", "Bsa", "Bufori", "Bugatti", "Bugre", "Buick", "Bullet", "Byd", "Bantam", "Benz", "Berliet", "Bitter", "Bmc", "Bnc", "Bond", "Borgward", "Brasier", "Brevetti fiat", "Bricklin"],
    "C": ["Cadillac", "Callaway", "Campagna", "Cardi", "Carlsson", "Casalini", "Caterham", "Chamonix", "Changan", "Changhe", "Chatenet", "Chenglong", "Chevrolet", "Chevron", "Chrysler", "Citroën", "Cobra", "Consolier", "Courage", "Cunningham", "Carabela", "Carmel", "Ceirano", "Chalmers", "Chandler", "Chaparral", "Checker", "Cheetah", "Chenard & walcker", "Cisitalia", "Cizeta-moroder", "Clan", "Clipper", "Cord"],
    "D": ["Dacia", "Daewoo", "Daf", "Daihatsu", "Daimler", "Dare", "Dart", "Dauer", "Dax", "Delfino", "Delorean", "De tomaso", "Dodge", "Dome", "Donkervoort", "Dutton", "Daf", "Darracq", "Datsun", "De dion-bouton", "Delage", "Delahaye", "Dellow", "Delorean", "Desoto", "Dfp", "Disa", "Dixi", "Dkw", "Dort", "Duesenberg", "Dufaux"],
    "E": ["Eagle", "E.b.m.", "Edag", "Edra", "Elcat", "Emis", "Etsong", "Edsel", "Elva", "Emw", "Essex", "Excalibur", "Excelsior"],
    "F": ["Fabral", "Faw", "Feng huang", "Fengshen", "Ferrari", "Fiat", "Fioravanti", "Ford", "Freightliner", "Fsm", "Fso", "Fuso", "Facel-vega", "Fairthorpe", "Fast", "Florentia", "Fmr", "F.n.", "Framo", "Frazer-nash", "Fuldamobil"],
    "G": ["Gas", "Geely", "Geo", "Gigliato", "Gillet", "Gmc", "Grecave", "Guangzhou", "Gurgel", "Gaggenau", "General", "Germain", "Gilbern", "Ginetta", "Glas", "Goggomobil", "Gordon-keeble", "Graef & stift"],
    "H": ["Hafei", "Haima", "Haldesign", "Hanjiang", "Hauser", "Heibao", "Heuliez", "Hindustan", "Holden", "Hommer", "Honda", "Honda mugen", "Hongqi", "Hmc", "Hsv", "Huayang", "Hummer", "Hyundai", "Historische automarken", "Hanomag", "Hampton", "Heinkel", "Hillman", "Hispano-suiza", "Horch", "Hupmobile", "Hudson", "Humber"],
    "I": ["Infiniti", "Innocenti", "Innotech", "Iran khodro", "Isdera", "Isuzu", "Italdesign", "Iveco", "Izh", "Imperia", "Ifa", "Isotta fraschini", "Itala"],
    "J": ["Jaguar", "Jalta", "Jdm", "Jeep", "Jensen", "Jetcar", "Jie fang", "Jilin", "Jimenez", "Jinbei", "Jiotta", "Josse car", "Jva", "James and browne", "Jawa", "Jowett", "Jensen healey", "Jensen"],
    "K": ["Karmann", "Keinath", "Kewet", "Kia", "Koenigsegg", "Kaiser", "Kissel", "Kleinschnittger"],
    "L": ["Lada", "Lamborghini", "Lancia", "Land rover", "Laraki", "Leblanc", "Lexus", "Ligier", "Lincoln", "Lobini", "Lola", "Lotec", "Lotus", "Lti", "Lynx", "Lago", "Lagonda", "Lanchester", "Lasalle", "Laurin & klement", "Lea-francis", "Leyland", "Liberty", "Lightburn", "Lister", "Lloyd", "Locomobile", "Locost", "Lorraine-dietrich", "Lanchester"],
    "M": ["Mag", "Mahindra", "Marcos", "Maruti", "Maserati", "Matra", "Maybach", "Mazda", "Mcv", "Mclaren", "Mega", "Mercedes-benz", "Mercury", "Merkur", "Merlin", "Mg", "Microcar", "Mini", "Mitsubishi", "Mitsuoka", "Monte carlo", "Morgan", "Moskwitsch", "Mosler", "Mullen", "Magirus-deutz", "Marlin", "Marmon", "Martini", "Mauser", "Maxwell-briscoe", "Mercedes", "Mcfarlan", "Mclaughlin", "Melkus", "Mercer", "Messerschmitt", "Metallurgique", "Miele", "Miesse", "Minerva", "Monteverdi", "Morris", "Muntz"],
    "N": ["Nismo", "Nissan", "Noble", "Nsu", "Nagant", "Napier", "Nash healey", "Nash", "Nordenfelt", "Nsu", "Nuffield"],
    "O": ["Obvio", "Oka", "Oldsmobile", "Oltcit", "Opel", "Osca", "Otosan", "Oakland", "Ogle", "Orient express", "Overland"],
    "P": ["Pagani", "Panoz", "Parradine", "Performance", "Peugeot", "Pilbeam", "Piotek", "Plymouth", "Pontiac", "Porsche", "Prmeier", "Proton", "Puma", "Packard", "Pegaso", "Panhard & levassor", "Panther", "Peerless", "Pic pic", "Pierce-arrow", "Pipe", "Pobeda", "Polski fiat", "Praga", "Presto", "Prince motors", "Princess", "Puch"],
    "Q": ["Qvale mangusta"],
    "R": ["Reliant", "Renault", "Reva", "Reynard", "Rinspeed", "Rolls-royce", "Ronart", "Rongcheng", "Rover", "Rush", "Rambler", "Ramses", "Riley", "Rochdale", "Rootes", "Roehr", "Rumpler"],
    "S": ["Saab", "Saker", "Saleen", "San storm", "Saporoshez", "Saturn", "Savel", "Sbarro", "Schuppan", "Scion", "Seat", "Sensor", "Setra", "Shamrock", "Shanghai", "Shelby", "Short", "Sipani", "Skoda", "Smart", "Spectre", "Spyker", "Ssang yong", "Stealth", "Sterling", "Sterling trucks", "Steyr-puch", "Stola", "Strathcarron", "Subaru", "Super seven", "Suzuki", "Swift", "Sachsenring", "Scat", "Serenka", "Serpollet", "Siata", "Simca", "Simca-matra", "Singer", "Sizaire & naudin", "Sommer", "Spartan", "Speedwell", "Ss", "Standard", "Stoewer", "Studebaker", "Stutz", "Sunbeam", "Sunbeam-talbot", "Susita", "Syrena"],
    "T": ["Tata", "Tatra", "Tempo", "Think", "Thomond", "Tiger", "Tjorven", "Tofas", "Tokchon", "Tommy", "Toyota", "Treser", "Troller", "Tschajka", "Tvr", "Twike", "Takuri", "Talbot", "Talbot-darrac", "Talbot-lago", "Tornado", "Trident", "Triumph", "Triumph", "Trojan", "Tucker", "Turicum", "Turner", "Tesla"],
    "U": ["Uaz", "Ultima", "Ural", "Unic", "Unipower"],
    "V": ["Vauxhall", "Vaz", "Vector", "Vemac", "Venturi", "Veritas", "Vision", "Volkswagen", "Volvo", "Vanden plas", "Vivinus"],
    "W": ["Welter racing", "Western star trucks", "Westfield", "Wiesmann", "Witton tiger", "Wolga", "Wanderer", "Walter", "Warszawa", "Wartburg", "Weber", "White", "Wikov", "Willys", "Winton", "Wolseley"],
    "X": ["Xiali"],
    "Y": ["Yes", "Yuejin", "Yugo"],
    "Z": ["Zagato", "Zastava", "Zaz", "Zender", "Zhonghua", "Zhongxing", "Zil"]
  }

};
